v2.7.0 public release

diff --git a/src/images/common/connector/Dockerfile b/src/images/common/connector/Dockerfile
--- a/src/images/common/connector/Dockerfile
+++ b/src/images/common/connector/Dockerfile
@@ -1,29 +1,12 @@
-# MIT License
+# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
+# © N.Harris Computer Corporation (2022)
 #
-# Copyright (c) 2022, N. Harris Computer Corporation
-#
-# Permission is hereby granted, free of charge, to any person obtaining a copy
-# of this software and associated documentation files (the "Software"), to deal
-# in the Software without restriction, including without limitation the rights
-# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-# copies of the Software, and to permit persons to whom the Software is
-# furnished to do so, subject to the following conditions:
-#
-# The above copyright notice and this permission notice shall be included in all
-# copies or substantial portions of the Software.
-#
-# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
-# SOFTWARE.
+# SPDX short identifier: MIT
 
 FROM ubuntu:18.04
 
 LABEL maintainer="i2group"
-LABEL version="2.6.1"
+LABEL version="2.7.0"
 
 #Install the prerequisites.
 RUN apt-get update && \
@@ -44,22 +27,22 @@ RUN useradd -m -g i2analyze i2analyze
 RUN groupadd keys && usermod -a -G keys i2analyze
 
 #Use the extracted toolkit from the ubuntu_toolkit_image to copy the example connector to the image.
-COPY --chown=i2analyze:i2analyze --from=ubuntu_toolkit_image /opt/IBM/i2analyze/toolkit/examples/connectors/example-connector /opt/IBM/i2analyze/example_connector
+COPY --chown=i2analyze:i2analyze --from=ubuntu_toolkit_image /opt/i2/i2analyze/toolkit/examples/connectors/example-connector /opt/i2/i2analyze/example_connector
 
 #Add the startupExt file for future startup commands
-COPY --chown=i2analyze:i2analyze --from=ubuntu_toolkit_image /opt/IBM/startupExt /opt/IBM/startupExt
+COPY --chown=i2analyze:i2analyze --from=ubuntu_toolkit_image /opt/i2/startupExt /opt/i2/startupExt
 
 #Add the populated security-config.json for the example connector to the connector image.
-COPY --chown=i2analyze:i2analyze security-config.json /opt/IBM/i2analyze/example_connector/security-config.json
+COPY --chown=i2analyze:i2analyze security-config.json /opt/i2/i2analyze/example_connector/security-config.json
 
 #Copy the utils to the container.
-COPY --chown=i2analyze:i2analyze --from=ubuntu_toolkit_image /opt/IBM/utils /opt/IBM/utils
+COPY --chown=i2analyze:i2analyze --from=ubuntu_toolkit_image /opt/i2/utils /opt/i2/utils
 
 #Remove hard coded reference to user random file
 #see https://github.com/openssl/openssl/issues/7754
 RUN sed -i -E 's/^(RANDFILE.*HOME.*)/#\1/' /etc/ssl/openssl.cnf
 
-WORKDIR /opt/IBM/i2analyze/example_connector
+WORKDIR /opt/i2/i2analyze/example_connector
 
 #Install the prerequisites for the example connector.
 RUN npm install
@@ -67,9 +50,9 @@ RUN npm install
 USER i2analyze:i2analyze
 
 #Start the example connector.
-RUN echo "nodejs /opt/IBM/i2analyze/example_connector/app.js || echo \"Error starting example connector\"" >> /opt/IBM/startupExt
+RUN echo "nodejs /opt/i2/i2analyze/example_connector/app.js || echo \"Error starting example connector\"" >> /opt/i2/startupExt
 
 #Expose the port that the example connector uses.
 EXPOSE 3700
 
-ENTRYPOINT /opt/IBM/startupExt && tail -f /dev/null
+ENTRYPOINT /opt/i2/startupExt && tail -f /dev/null
diff --git a/src/images/common/zookeeper2/Dockerfile b/src/images/common/zookeeper2/Dockerfile
--- a/src/images/common/zookeeper2/Dockerfile
+++ b/src/images/common/zookeeper2/Dockerfile
@@ -1,24 +1,7 @@
-# MIT License
+# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
+# © N.Harris Computer Corporation (2022)
 #
-# Copyright (c) 2022, N. Harris Computer Corporation
-#
-# Permission is hereby granted, free of charge, to any person obtaining a copy
-# of this software and associated documentation files (the "Software"), to deal
-# in the Software without restriction, including without limitation the rights
-# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-# copies of the Software, and to permit persons to whom the Software is
-# furnished to do so, subject to the following conditions:
-#
-# The above copyright notice and this permission notice shall be included in all
-# copies or substantial portions of the Software.
-#
-# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
-# SOFTWARE.
+# SPDX short identifier: MIT
 
 FROM ubuntu_toolkit_image
 
@@ -33,12 +16,12 @@ COPY --chown=i2analyze:i2analyze configuration ${toolkitDir}/configuration
 USER i2analyze:i2analyze
 
 #Install ZooKeeper.
-RUN /opt/IBM/i2analyze/toolkit/scripts/setup -t installZookeeper
+RUN /opt/i2/i2analyze/toolkit/scripts/setup -t installZookeeper
 
 #Create the ZooKeeper host and the configuration for the ZooKeeper hosts on this server.
-RUN /opt/IBM/i2analyze/toolkit/scripts/setup -t createZkHosts --hostname ${hostname}
+RUN /opt/i2/i2analyze/toolkit/scripts/setup -t createZkHosts --hostname ${hostname}
 
-RUN echo "/opt/IBM/i2analyze/toolkit/scripts/setup -t startZkHosts --hostname ${hostname} || echo \"Error stating Zookeeper host in ${hostname}\"" >> /opt/IBM/startupExt
+RUN echo "/opt/i2/i2analyze/toolkit/scripts/setup -t startZkHosts --hostname ${hostname} || echo \"Error stating Zookeeper host in ${hostname}\"" >> /opt/i2/startupExt
 
 #Start ZooKeeper and upload the Solr configuration to ZooKeeper.
-ENTRYPOINT /opt/IBM/startupExt && tail -f /dev/null
+ENTRYPOINT /opt/i2/startupExt && tail -f /dev/null
diff --git a/src/images/db2/db2/Dockerfile b/src/images/db2/db2/Dockerfile
--- a/src/images/db2/db2/Dockerfile
+++ b/src/images/db2/db2/Dockerfile
@@ -1,24 +1,7 @@
-# MIT License
+# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
+# © N.Harris Computer Corporation (2022)
 #
-# Copyright (c) 2022, N. Harris Computer Corporation
-#
-# Permission is hereby granted, free of charge, to any person obtaining a copy
-# of this software and associated documentation files (the "Software"), to deal
-# in the Software without restriction, including without limitation the rights
-# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-# copies of the Software, and to permit persons to whom the Software is
-# furnished to do so, subject to the following conditions:
-#
-# The above copyright notice and this permission notice shall be included in all
-# copies or substantial portions of the Software.
-#
-# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
-# SOFTWARE.
+# SPDX short identifier: MIT
 
 FROM db2_installer_image
 
@@ -37,7 +20,7 @@ COPY --chown=db2inst1:db2iadm1 db2nodes.cfg /home/db2inst1/sqllib/db2nodes.cfg
 #Create a group for securing the keys
 RUN usermod -a -G keys db2inst1
 
-RUN echo ". /home/db2inst1/sqllib/db2profile && db2start || echo \"Error starting DB2\"" >> /opt/IBM/startupExt
+RUN echo ". /home/db2inst1/sqllib/db2profile && db2start || echo \"Error starting DB2\"" >> /opt/i2/startupExt
 
 USER db2inst1:db2iadm1
 
@@ -45,4 +28,4 @@ RUN /home/db2inst1/sqllib/adm/db2licm -a /opt/IBM/adv_vpc/db2/license/db2adv_vpc
 
 EXPOSE 50000 50001
 
-ENTRYPOINT /opt/IBM/startupExt && tail -f /dev/null
+ENTRYPOINT /opt/i2/startupExt && tail -f /dev/null
diff --git a/src/images/sqlserver/liberty/Dockerfile b/src/images/sqlserver/liberty/Dockerfile
--- a/src/images/sqlserver/liberty/Dockerfile
+++ b/src/images/sqlserver/liberty/Dockerfile
@@ -1,31 +1,14 @@
-# MIT License
+# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
+# © N.Harris Computer Corporation (2022)
 #
-# Copyright (c) 2022, N. Harris Computer Corporation
-#
-# Permission is hereby granted, free of charge, to any person obtaining a copy
-# of this software and associated documentation files (the "Software"), to deal
-# in the Software without restriction, including without limitation the rights
-# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-# copies of the Software, and to permit persons to whom the Software is
-# furnished to do so, subject to the following conditions:
-#
-# The above copyright notice and this permission notice shall be included in all
-# copies or substantial portions of the Software.
-#
-# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
-# SOFTWARE.
+# SPDX short identifier: MIT
 
 FROM mcr.microsoft.com/mssql-tools
 
 LABEL maintainer="i2group"
-LABEL version="2.6.1"
+LABEL version="2.7.0"
 
-ENV i2analyzeDir /opt/IBM/i2analyze
+ENV i2analyzeDir /opt/i2/i2analyze
 ENV toolkitDir ${i2analyzeDir}/toolkit
 
 #Install the prerequisites.
@@ -46,10 +29,10 @@ RUN groupadd keys && usermod -a -G keys i2analyze
 COPY --chown=i2analyze:i2analyze --from=ubuntu_toolkit_image ${i2analyzeDir} ${i2analyzeDir}
 
 #Add the startupExt file for future startup commands
-COPY --chown=i2analyze:i2analyze --from=ubuntu_toolkit_image /opt/IBM/startupExt /opt/IBM/startupExt
+COPY --chown=i2analyze:i2analyze --from=ubuntu_toolkit_image /opt/i2/startupExt /opt/i2/startupExt
 
 #Copy utils
-COPY --chown=i2analyze:i2analyze --from=ubuntu_toolkit_image /opt/IBM/utils /opt/IBM/utils
+COPY --chown=i2analyze:i2analyze --from=ubuntu_toolkit_image /opt/i2/utils /opt/i2/utils
 
 #The custom configuration overrides the base configuration in the ubuntu_toolkit_image.
 COPY --chown=i2analyze:i2analyze configuration ${toolkitDir}/configuration
@@ -65,11 +48,11 @@ RUN ${toolkitDir}/scripts/setup -t deployLiberty
 
 #Create an example user registry in Liberty.
 RUN ${toolkitDir}/scripts/setup -t ensureExampleUserRegistry
-COPY --chown=i2analyze:i2analyze user.registry.xml /opt/IBM/i2analyze/deploy/wlp/usr/shared/config/
+COPY --chown=i2analyze:i2analyze user.registry.xml /opt/i2/i2analyze/deploy/wlp/usr/shared/config/
 
-RUN echo "export JAVA_HOME=/opt/IBM/i2analyze/deploy/java && /opt/IBM/i2analyze/toolkit/scripts/setup -t startLiberty || echo \"Error starting Liberty\"" >> /opt/IBM/startupExt
+RUN echo "export JAVA_HOME=/opt/i2/i2analyze/deploy/java && /opt/i2/i2analyze/toolkit/scripts/setup -t startLiberty || echo \"Error starting Liberty\"" >> /opt/i2/startupExt
 
 EXPOSE 9082 9445
 
 #Start the Liberty server that hosts i2 Analyze.
-ENTRYPOINT /opt/IBM/startupExt && tail -f /dev/null
+ENTRYPOINT /opt/i2/startupExt && tail -f /dev/null
diff --git a/src/scripts/resetEnvironment b/src/scripts/resetEnvironment
--- a/src/scripts/resetEnvironment
+++ b/src/scripts/resetEnvironment
@@ -1,25 +1,8 @@
 #!/bin/bash
-# MIT License
+# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
+# © N.Harris Computer Corporation (2022)
 #
-# Copyright (c) 2022, N. Harris Computer Corporation
-#
-# Permission is hereby granted, free of charge, to any person obtaining a copy
-# of this software and associated documentation files (the "Software"), to deal
-# in the Software without restriction, including without limitation the rights
-# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-# copies of the Software, and to permit persons to whom the Software is
-# furnished to do so, subject to the following conditions:
-#
-# The above copyright notice and this permission notice shall be included in all
-# copies or substantial portions of the Software.
-#
-# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
-# SOFTWARE.
+# SPDX short identifier: MIT
 
 #####################################################################################
 #                                                                                   #
@@ -46,23 +29,23 @@ if [[ $dbDialect != "sqlserver" &&  $dbDialect != "db2" ]]; then
 fi
 
 output "Remove the configuration directory on each container"
-docker exec admin_client sh -c "rm -rf /opt/IBM/i2analyze/toolkit/configuration/*"
-docker exec liberty sh -c "rm -rf /opt/IBM/i2analyze/toolkit/configuration/*"
-docker exec zookeeper sh -c "rm -rf /opt/IBM/i2analyze/toolkit/configuration/*"
-docker exec zookeeper2 sh -c "rm -rf /opt/IBM/i2analyze/toolkit/configuration/*"
-docker exec zookeeper3 sh -c "rm -rf /opt/IBM/i2analyze/toolkit/configuration/*"
-docker exec solr sh -c "rm -rf /opt/IBM/i2analyze/toolkit/configuration/*"
-docker exec solr2 sh -c "rm -rf /opt/IBM/i2analyze/toolkit/configuration/*"
+docker exec admin_client sh -c "rm -rf /opt/i2/i2analyze/toolkit/configuration/*"
+docker exec liberty sh -c "rm -rf /opt/i2/i2analyze/toolkit/configuration/*"
+docker exec zookeeper sh -c "rm -rf /opt/i2/i2analyze/toolkit/configuration/*"
+docker exec zookeeper2 sh -c "rm -rf /opt/i2/i2analyze/toolkit/configuration/*"
+docker exec zookeeper3 sh -c "rm -rf /opt/i2/i2analyze/toolkit/configuration/*"
+docker exec solr sh -c "rm -rf /opt/i2/i2analyze/toolkit/configuration/*"
+docker exec solr2 sh -c "rm -rf /opt/i2/i2analyze/toolkit/configuration/*"
 
 output "Copy the configuration from the src/configuration directory to each container"
 #Copy Base Config
-docker cp "${BASE_CONFIG_PATH}/." admin_client:/opt/IBM/i2analyze/toolkit/configuration
-docker cp "${BASE_CONFIG_PATH}/." liberty:/opt/IBM/i2analyze/toolkit/configuration
-docker cp "${BASE_CONFIG_PATH}/." zookeeper:/opt/IBM/i2analyze/toolkit/configuration
-docker cp "${BASE_CONFIG_PATH}/." zookeeper2:/opt/IBM/i2analyze/toolkit/configuration
-docker cp "${BASE_CONFIG_PATH}/." zookeeper3:/opt/IBM/i2analyze/toolkit/configuration
-docker cp "${BASE_CONFIG_PATH}/." solr:/opt/IBM/i2analyze/toolkit/configuration
-docker cp "${BASE_CONFIG_PATH}/." solr2:/opt/IBM/i2analyze/toolkit/configuration
+docker cp "${BASE_CONFIG_PATH}/." admin_client:/opt/i2/i2analyze/toolkit/configuration
+docker cp "${BASE_CONFIG_PATH}/." liberty:/opt/i2/i2analyze/toolkit/configuration
+docker cp "${BASE_CONFIG_PATH}/." zookeeper:/opt/i2/i2analyze/toolkit/configuration
+docker cp "${BASE_CONFIG_PATH}/." zookeeper2:/opt/i2/i2analyze/toolkit/configuration
+docker cp "${BASE_CONFIG_PATH}/." zookeeper3:/opt/i2/i2analyze/toolkit/configuration
+docker cp "${BASE_CONFIG_PATH}/." solr:/opt/i2/i2analyze/toolkit/configuration
+docker cp "${BASE_CONFIG_PATH}/." solr2:/opt/i2/i2analyze/toolkit/configuration
 
 #Reset base configuration
 cp -r "${CONFIG_MODS_PATH}/${dbDialect}/base/." "${DEFAULT_CONFIG_PATH}"
@@ -71,70 +54,70 @@ cp -r "${CONFIG_MODS_PATH}/${dbDialect}/base/." "${DEFAULT_CONFIG_PATH}"
 pushd ${SCRIPTS_PATH}
 . copyConfiguration $dbDialect
 popd
-docker cp "${IMAGES_PATH}/${dbDialect}/admin_client/configuration/." admin_client:/opt/IBM/i2analyze/toolkit/configuration
-docker cp "${IMAGES_PATH}/${dbDialect}/liberty/configuration/." liberty:/opt/IBM/i2analyze/toolkit/configuration
-docker cp "${IMAGES_PATH}/common/zookeeper/configuration/." zookeeper:/opt/IBM/i2analyze/toolkit/configuration
-docker cp "${IMAGES_PATH}/common/zookeeper2/configuration/." zookeeper2:/opt/IBM/i2analyze/toolkit/configuration
-docker cp "${IMAGES_PATH}/common/zookeeper3/configuration/." zookeeper3:/opt/IBM/i2analyze/toolkit/configuration
-docker cp "${IMAGES_PATH}/common/solr/configuration/." solr:/opt/IBM/i2analyze/toolkit/configuration
-docker cp "${IMAGES_PATH}/common/solr2/configuration/." solr2:/opt/IBM/i2analyze/toolkit/configuration
+docker cp "${IMAGES_PATH}/${dbDialect}/admin_client/configuration/." admin_client:/opt/i2/i2analyze/toolkit/configuration
+docker cp "${IMAGES_PATH}/${dbDialect}/liberty/configuration/." liberty:/opt/i2/i2analyze/toolkit/configuration
+docker cp "${IMAGES_PATH}/common/zookeeper/configuration/." zookeeper:/opt/i2/i2analyze/toolkit/configuration
+docker cp "${IMAGES_PATH}/common/zookeeper2/configuration/." zookeeper2:/opt/i2/i2analyze/toolkit/configuration
+docker cp "${IMAGES_PATH}/common/zookeeper3/configuration/." zookeeper3:/opt/i2/i2analyze/toolkit/configuration
+docker cp "${IMAGES_PATH}/common/solr/configuration/." solr:/opt/i2/i2analyze/toolkit/configuration
+docker cp "${IMAGES_PATH}/common/solr2/configuration/." solr2:/opt/i2/i2analyze/toolkit/configuration
 
 #Change the ownership of the copied files
-docker exec -u root admin_client chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration
-docker exec -u root liberty chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration
-docker exec -u root zookeeper chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration
-docker exec -u root zookeeper2 chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration
-docker exec -u root zookeeper3 chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration
-docker exec -u root solr chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration
-docker exec -u root solr2 chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration
+docker exec -u root admin_client chown -R i2analyze:i2analyze /opt/i2/i2analyze/toolkit/configuration
+docker exec -u root liberty chown -R i2analyze:i2analyze /opt/i2/i2analyze/toolkit/configuration
+docker exec -u root zookeeper chown -R i2analyze:i2analyze /opt/i2/i2analyze/toolkit/configuration
+docker exec -u root zookeeper2 chown -R i2analyze:i2analyze /opt/i2/i2analyze/toolkit/configuration
+docker exec -u root zookeeper3 chown -R i2analyze:i2analyze /opt/i2/i2analyze/toolkit/configuration
+docker exec -u root solr chown -R i2analyze:i2analyze /opt/i2/i2analyze/toolkit/configuration
+docker exec -u root solr2 chown -R i2analyze:i2analyze /opt/i2/i2analyze/toolkit/configuration
 
 # If HTTP Server exists then reset the configuration
 contExists="$(containerExists ihs)"
 if [[ "$contExists" -eq 1 ]]; then
-    docker exec ihs sh -c "rm -rf /opt/IBM/i2analyze/toolkit/configuration/*"
-    docker cp "${IMAGES_PATH}/common/ihs/configuration/." ihs:/opt/IBM/i2analyze/toolkit/configuration
-    docker exec -u root ihs chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration
+    docker exec ihs bash -c "rm -rf /opt/i2/i2analyze/toolkit/configuration/*"
+    docker cp "${IMAGES_PATH}/common/ihs/configuration/." ihs:/opt/i2/i2analyze/toolkit/configuration
+    docker exec -u root ihs chown -R i2analyze:i2analyze /opt/i2/i2analyze/toolkit/configuration
 fi
 
 # Searching and replacing ssl tag, removing clientAuthenticationSupported
-docker exec -u i2analyze liberty sh -c "cd /opt/IBM/i2analyze/deploy/wlp/usr/servers/opal-server && \
+docker exec -u i2analyze liberty sh -c "cd /opt/i2/i2analyze/deploy/wlp/usr/servers/opal-server && \
     sed -i 's/<ssl sslProtocol=\"TLSv1.2\" clientAuthenticationSupported=\"true\" id=\"defaultSSLConfig\"/<ssl sslProtocol=\"TLSv1.2\" id=\"defaultSSLConfig\"/g' server.xml"
 
 # Search and replace httpDispatcher tag, removing trustedSensitiveHeaderOrigin
-docker exec -u i2analyze liberty sh -c "cd /opt/IBM/i2analyze/deploy/wlp/usr/servers/opal-server && \
+docker exec -u i2analyze liberty sh -c "cd /opt/i2/i2analyze/deploy/wlp/usr/servers/opal-server && \
     sed -i 's/trustedSensitiveHeaderOrigin=\"\*\"//g' server.xml"
 
 # Resetting start extensions
-docker exec -u root -it solr sh -c "echo \"/opt/IBM/i2analyze/toolkit/scripts/setup -t startSolrNodes --hostname solr.eianet || echo \"Error stating Solr node in solr\"\" > /opt/IBM/startupExt"
-docker exec -u root -it solr2 sh -c "echo \"/opt/IBM/i2analyze/toolkit/scripts/setup -t startSolrNodes --hostname solr2.eianet || echo \"Error stating Solr node in solr2\"\" > /opt/IBM/startupExt"
-docker exec -u root -it admin_client sh -c "echo \"\" > /opt/IBM/startupExt"
-docker exec -u root -it liberty sh -c "echo \"export JAVA_HOME=/opt/IBM/i2analyze/deploy/java && /opt/IBM/i2analyze/toolkit/scripts/setup -t startLiberty || echo \"Error starting Liberty\"\" > /opt/IBM/startupExt"
-docker exec -u root -it zookeeper sh -c "echo \"/opt/IBM/i2analyze/toolkit/scripts/setup -t startZkHosts --hostname zookeeeper.eianet || echo \"Error stating Zookeeper host in zookeeeper\"\" > /opt/IBM/startupExt"
-docker exec -u root -it zookeeper2 sh -c "echo \"/opt/IBM/i2analyze/toolkit/scripts/setup -t startZkHosts --hostname zookeeeper2.eianet || echo \"Error stating Zookeeper host in zookeeeper2\"\" > /opt/IBM/startupExt"
-docker exec -u root -it zookeeper3 sh -c "echo \"/opt/IBM/i2analyze/toolkit/scripts/setup -t startZkHosts --hostname zookeeeper3.eianet || echo \"Error stating Zookeeper host in zookeeeper3\"\" > /opt/IBM/startupExt"
+docker exec -u root -it solr sh -c "echo \"/opt/i2/i2analyze/toolkit/scripts/setup -t startSolrNodes --hostname solr.eianet || echo \"Error stating Solr node in solr\"\" > /opt/i2/startupExt"
+docker exec -u root -it solr2 sh -c "echo \"/opt/i2/i2analyze/toolkit/scripts/setup -t startSolrNodes --hostname solr2.eianet || echo \"Error stating Solr node in solr2\"\" > /opt/i2/startupExt"
+docker exec -u root -it admin_client sh -c "echo \"\" > /opt/i2/startupExt"
+docker exec -u root -it liberty sh -c "echo \"export JAVA_HOME=/opt/i2/i2analyze/deploy/java && /opt/i2/i2analyze/toolkit/scripts/setup -t startLiberty || echo \"Error starting Liberty\"\" > /opt/i2/startupExt"
+docker exec -u root -it zookeeper sh -c "echo \"/opt/i2/i2analyze/toolkit/scripts/setup -t startZkHosts --hostname zookeeeper.eianet || echo \"Error stating Zookeeper host in zookeeeper\"\" > /opt/i2/startupExt"
+docker exec -u root -it zookeeper2 sh -c "echo \"/opt/i2/i2analyze/toolkit/scripts/setup -t startZkHosts --hostname zookeeeper2.eianet || echo \"Error stating Zookeeper host in zookeeeper2\"\" > /opt/i2/startupExt"
+docker exec -u root -it zookeeper3 sh -c "echo \"/opt/i2/i2analyze/toolkit/scripts/setup -t startZkHosts --hostname zookeeeper3.eianet || echo \"Error stating Zookeeper host in zookeeeper3\"\" > /opt/i2/startupExt"
 
 output "Resetting configuration"
-docker exec -u i2analyze liberty /opt/IBM/i2analyze/toolkit/scripts/setup -t stopLiberty
+docker exec -u i2analyze liberty /opt/i2/i2analyze/toolkit/scripts/setup -t stopLiberty
 
 # Resetting the Solr configuration in the Zookeeper servers
-docker exec -u i2analyze admin_client /opt/IBM/i2analyze/toolkit/scripts/setup -t createAndUploadSolrConfig --hostname admin_client.eianet
+docker exec -u i2analyze admin_client /opt/i2/i2analyze/toolkit/scripts/setup -t createAndUploadSolrConfig --hostname admin_client.eianet
 
 # Restarting zookeeper containers
-docker exec -u i2analyze zookeeper /opt/IBM/i2analyze/toolkit/scripts/setup -t stopZkHosts --hostname zookeeper.eianet
-docker exec -u i2analyze zookeeper /opt/IBM/i2analyze/toolkit/scripts/setup -t startZkHosts --hostname zookeeper.eianet
+docker exec -u i2analyze zookeeper /opt/i2/i2analyze/toolkit/scripts/setup -t stopZkHosts --hostname zookeeper.eianet
+docker exec -u i2analyze zookeeper /opt/i2/i2analyze/toolkit/scripts/setup -t startZkHosts --hostname zookeeper.eianet
 
-docker exec -u i2analyze zookeeper2 /opt/IBM/i2analyze/toolkit/scripts/setup -t stopZkHosts --hostname zookeeper2.eianet
-docker exec -u i2analyze zookeeper2 /opt/IBM/i2analyze/toolkit/scripts/setup -t startZkHosts --hostname zookeeper2.eianet
+docker exec -u i2analyze zookeeper2 /opt/i2/i2analyze/toolkit/scripts/setup -t stopZkHosts --hostname zookeeper2.eianet
+docker exec -u i2analyze zookeeper2 /opt/i2/i2analyze/toolkit/scripts/setup -t startZkHosts --hostname zookeeper2.eianet
 
-docker exec -u i2analyze zookeeper3 /opt/IBM/i2analyze/toolkit/scripts/setup -t stopZkHosts --hostname zookeeper3.eianet
-docker exec -u i2analyze zookeeper3 /opt/IBM/i2analyze/toolkit/scripts/setup -t startZkHosts --hostname zookeeper3.eianet
+docker exec -u i2analyze zookeeper3 /opt/i2/i2analyze/toolkit/scripts/setup -t stopZkHosts --hostname zookeeper3.eianet
+docker exec -u i2analyze zookeeper3 /opt/i2/i2analyze/toolkit/scripts/setup -t startZkHosts --hostname zookeeper3.eianet
 
 # Restarting solr containers
-docker exec -u i2analyze solr /opt/IBM/i2analyze/toolkit/scripts/setup -t stopSolrNodes --hostname solr.eianet
-docker exec -u i2analyze solr2 /opt/IBM/i2analyze/toolkit/scripts/setup -t stopSolrNodes --hostname solr2.eianet
+docker exec -u i2analyze solr /opt/i2/i2analyze/toolkit/scripts/setup -t stopSolrNodes --hostname solr.eianet
+docker exec -u i2analyze solr2 /opt/i2/i2analyze/toolkit/scripts/setup -t stopSolrNodes --hostname solr2.eianet
 
-docker exec -u i2analyze solr /opt/IBM/i2analyze/toolkit/scripts/setup -t startSolrNodes --hostname solr.eianet
-docker exec -u i2analyze solr2 /opt/IBM/i2analyze/toolkit/scripts/setup -t startSolrNodes --hostname solr2.eianet
+docker exec -u i2analyze solr /opt/i2/i2analyze/toolkit/scripts/setup -t startSolrNodes --hostname solr.eianet
+docker exec -u i2analyze solr2 /opt/i2/i2analyze/toolkit/scripts/setup -t startSolrNodes --hostname solr2.eianet
 
 if [[ $dbDialect == "db2" ]]; then
     # Resetting the DB2COMM property in the db2 server
@@ -143,12 +126,12 @@ if [[ $dbDialect == "db2" ]]; then
     docker exec -u db2inst1 -t db2 bash -c ". /home/db2inst1/sqllib/db2profile && db2 update dbm cfg using SSL_VERSIONS NULL"
 
     # Recataloging the database on the admin_client container
-    docker exec -u i2analyze admin_client bash -c ". /home/db2inst1/sqllib/db2profile && /opt/IBM/i2analyze/toolkit/scripts/setup -t recatalogRemoteDB2Nodes"
-    docker exec -u i2analyze admin_client bash -c ". /home/db2inst1/sqllib/db2profile && /opt/IBM/i2analyze/toolkit/scripts/setup -t recatalogDB2Databases"
+    docker exec -u i2analyze admin_client bash -c ". /home/db2inst1/sqllib/db2profile && /opt/i2/i2analyze/toolkit/scripts/setup -t recatalogRemoteDB2Nodes"
+    docker exec -u i2analyze admin_client bash -c ". /home/db2inst1/sqllib/db2profile && /opt/i2/i2analyze/toolkit/scripts/setup -t recatalogDB2Databases"
 
     # Recataloging the database on the liberty container
-    docker exec -u i2analyze liberty bash -c ". /home/db2inst1/sqllib/db2profile && /opt/IBM/i2analyze/toolkit/scripts/setup -t recatalogRemoteDB2Nodes"
-    docker exec -u i2analyze liberty bash -c ". /home/db2inst1/sqllib/db2profile && /opt/IBM/i2analyze/toolkit/scripts/setup -t recatalogDB2Databases"
+    docker exec -u i2analyze liberty bash -c ". /home/db2inst1/sqllib/db2profile && /opt/i2/i2analyze/toolkit/scripts/setup -t recatalogRemoteDB2Nodes"
+    docker exec -u i2analyze liberty bash -c ". /home/db2inst1/sqllib/db2profile && /opt/i2/i2analyze/toolkit/scripts/setup -t recatalogDB2Databases"
 elif [[ $dbDialect == "sqlserver" ]]; then
     # Resetting the connection properties in the sqlserver server
     docker exec -t sqlserver /opt/mssql/bin/mssql-conf unset network.tlscert
@@ -158,7 +141,7 @@ elif [[ $dbDialect == "sqlserver" ]]; then
 fi
 
 # Deploying liberty
-docker exec -u i2analyze liberty /opt/IBM/i2analyze/toolkit/scripts/setup -t deployLiberty
+docker exec -u i2analyze liberty /opt/i2/i2analyze/toolkit/scripts/setup -t deployLiberty
 
 if [[ $dbDialect == "db2" ]]; then
     # Restart db2
@@ -170,6 +153,6 @@ elif [[ $dbDialect == "sqlserver" ]]; then
 fi
 
 # Starting liberty
-docker exec -u i2analyze liberty /opt/IBM/i2analyze/toolkit/scripts/setup -t startLiberty
+docker exec -u i2analyze liberty /opt/i2/i2analyze/toolkit/scripts/setup -t startLiberty
 
 popd
