V2.0.0 public release

diff --git a/src/scripts/copyConfiguration b/src/scripts/copyConfiguration
--- a/src/scripts/copyConfiguration
+++ b/src/scripts/copyConfiguration
@@ -14,7 +14,8 @@
 #                                                                                   #
 #  Script to copy default configuration into image folders for building images.     #
 #                                                                                   #
-#  Usage : copyConfiguration                                                        #
+#  Usage : copyConfiguration [<dbDialect>]                                          #
+#  Defaults to current dialect                                                      #
 #                                                                                   #
 #####################################################################################
 
@@ -26,20 +27,40 @@ pushd ..
 
 . ${UTILS_PATH}/functions
 
+dbDialect=${1:-${DB_DIALECT}}
+
+if [[ $dbDialect != "sqlserver" &&  $dbDialect != "db2" ]]; then
+    echo "Error: Unrecognized dialect."
+    exit 1
+fi
+
 output "Cleaning the user configuration"
-rm -rf ${IMAGES_PATH}/liberty/configuration &>/dev/null || true
-rm -rf ${IMAGES_PATH}/zookeeper/configuration &>/dev/null || true
-rm -rf ${IMAGES_PATH}/solr/configuration &>/dev/null || true
-rm -rf ${IMAGES_PATH}/solr2/configuration &>/dev/null || true
-rm -rf ${IMAGES_PATH}/admin_client/configuration &>/dev/null || true
-rm -rf ${IMAGES_PATH}/ihs/configuration &>/dev/null || true
+#Common contexts
+rm -rf "${IMAGES_PATH}/common/zookeeper/configuration" &>/dev/null || true
+rm -rf "${IMAGES_PATH}/common/solr/configuration" &>/dev/null || true
+rm -rf "${IMAGES_PATH}/common/solr2/configuration" &>/dev/null || true
+rm -rf "${IMAGES_PATH}/common/ihs/configuration" &>/dev/null || true
+
+if [[ $dbDialect == "db2" ]]; then
+    #DB2 contexts
+    rm -rf "${IMAGES_PATH}/db2/liberty/configuration" &>/dev/null || true
+    rm -rf "${IMAGES_PATH}/db2/admin_client/configuration" &>/dev/null || true
+fi
+if [[ $dbDialect == "sqlserver" ]]; then
+    #Microsoft SQL contexts
+    rm -rf "${IMAGES_PATH}/sqlserver/liberty/configuration" &>/dev/null || true
+    rm -rf "${IMAGES_PATH}/sqlserver/admin_client/configuration" &>/dev/null || true
+fi
 
 output "Copying the user configuration into all of the required Docker contexts"
-cp -r ${DEFAULT_CONFIG_PATH} ${IMAGES_PATH}/liberty/configuration
-cp -r ${DEFAULT_CONFIG_PATH} ${IMAGES_PATH}/zookeeper/configuration
-cp -r ${DEFAULT_CONFIG_PATH} ${IMAGES_PATH}/solr/configuration
-cp -r ${DEFAULT_CONFIG_PATH} ${IMAGES_PATH}/solr2/configuration
-cp -r ${DEFAULT_CONFIG_PATH} ${IMAGES_PATH}/admin_client/configuration
-cp -r ${DEFAULT_CONFIG_PATH} ${IMAGES_PATH}/ihs/configuration
+#Common contexts
+cp -r "${DEFAULT_CONFIG_PATH}" "${IMAGES_PATH}/common/zookeeper/configuration"
+cp -r "${DEFAULT_CONFIG_PATH}" "${IMAGES_PATH}/common/solr/configuration"
+cp -r "${DEFAULT_CONFIG_PATH}" "${IMAGES_PATH}/common/solr2/configuration"
+cp -r "${DEFAULT_CONFIG_PATH}" "${IMAGES_PATH}/common/ihs/configuration"
+
+#Dialect specific
+cp -r "${DEFAULT_CONFIG_PATH}" "${IMAGES_PATH}/${dbDialect}/liberty/configuration"
+cp -r "${DEFAULT_CONFIG_PATH}" "${IMAGES_PATH}/${dbDialect}/admin_client/configuration"
 
 popd
diff --git a/src/scripts/deployDaod b/src/scripts/deployDaod
--- a/src/scripts/deployDaod
+++ b/src/scripts/deployDaod
@@ -14,8 +14,9 @@
 #                                                                                   #
 #  Script to set up i2 connect for use with i2 Analyze.                             #
 #                                                                                   #
-#  Usage : deployDaod [<configModsName>]                                            #
+#  Usage : deployDaod [<configModsName>] [<dbDialect>]                              #
 #  Defaults to i2connect configuration directory                                    #
+#  Defaults to current dialect                                                      #
 #                                                                                   #
 #####################################################################################
 
@@ -34,8 +35,14 @@ if [[ $configModsName != "i2connect" &&  $configModsName != "i2connect_istore" ]
     exit 1
 fi
 
+dbDialect=${2:-${DB_DIALECT}}
+if [[ $dbDialect != "sqlserver" &&  $dbDialect != "db2" ]]; then
+    echo "Error: Unrecognized dialect."
+    exit 1
+fi
+
 pushd ${SCRIPTS_PATH}
-. updateServerConfigurations ${configModsName}
+. updateServerConfigurations ${configModsName} ${dbDialect}
 popd
 
 output "Stopping Liberty"
@@ -51,7 +58,7 @@ output "Creating Solr collections"
 docker exec -t -u i2analyze admin_client /opt/IBM/i2analyze/toolkit/scripts/setup -t createSolrCollections --hostname admin_client
 
 output "Copying security configuration and restarting the connector container"
-docker cp ${IMAGES_PATH}/connector/security-config.json connector:/opt/IBM/i2analyze/example_connector/security-config.json
+docker cp ${IMAGES_PATH}/common/connector/security-config.json connector:/opt/IBM/i2analyze/example_connector/security-config.json
 # After the connector container is restarted, the example connector starts with the SSL configuration
 docker restart connector
 
diff --git a/src/scripts/deployEtlClient b/src/scripts/deployEtlClient
--- a/src/scripts/deployEtlClient
+++ b/src/scripts/deployEtlClient
@@ -10,13 +10,13 @@
 # *
 # ********************************************************************************/
 
- #####################################################################################
- #                                                                                   #
- #  Script to set up the etl_client for use and to ingest example data               #
- #                                                                                   #
- #  Usage : deployEtlClient                                                          #
- #                                                                                   #
- #####################################################################################
+#####################################################################################
+#                                                                                   #
+#  Script to set up the etl_client for use and to ingest example data               #
+#                                                                                   #
+#  Usage : deployEtlClient                                                          #
+#                                                                                   #
+#####################################################################################
 
 set -e
 
@@ -25,6 +25,13 @@ set -e
 pushd ..
 
 . ${UTILS_PATH}/functions
+
+dbDialect=${1:-${DB_DIALECT}}
+
+if [[ $dbDialect != "sqlserver" &&  $dbDialect != "db2" ]]; then
+    echo "Error: Unrecognized dialect."
+    exit 1
+fi
 
 output "Removing old etltoolkit from etl_client and admin_client if exists"
 docker exec -u i2analyze etl_client rm -Rf /opt/IBM/i2analyze/etltoolkit
@@ -39,6 +46,11 @@ docker exec -u i2analyze admin_client rm -Rf /opt/IBM/i2analyze/etltoolkit
 
 docker cp ./etltoolkit etl_client:/opt/IBM/i2analyze/etltoolkit
 rm -rf etltoolkit &>/dev/null || true
-docker exec -u root -it etl_client chown -R i2analyze:db2iusr1 /opt/IBM/i2analyze/
+
+if [[ $dbDialect == "sqlserver" ]]; then
+    docker exec -u root -it etl_client chown -R i2analyze:i2analyze /opt/IBM/i2analyze/
+else
+    docker exec -u root -it etl_client chown -R i2analyze:db2iusr1 /opt/IBM/i2analyze/
+fi
 
 popd
diff --git a/src/scripts/resetEnvironment b/src/scripts/resetEnvironment
--- a/src/scripts/resetEnvironment
+++ b/src/scripts/resetEnvironment
@@ -14,7 +14,8 @@
 #                                                                                   #
 #  Script to reset the environment to the default configuration.                    #
 #                                                                                   #
-#  Usage : resetEnvironment                                                         #
+#  Usage : resetEnvironment [<dbDialect>]                                           #
+#  Defaults to current dialect                                                      #
 #                                                                                   #
 #####################################################################################
 
@@ -25,6 +26,13 @@ set -e
 pushd ..
 
 . ${UTILS_PATH}/functions
+
+dbDialect=${1:-${DB_DIALECT}}
+
+if [[ $dbDialect != "sqlserver" &&  $dbDialect != "db2" ]]; then
+    echo "Error: Unrecognized dialect."
+    exit 1
+fi
 
 output "Remove the configuration directory on each container"
 docker exec admin_client sh -c "rm -rf /opt/IBM/i2analyze/toolkit/configuration/*"
@@ -40,29 +48,34 @@ docker cp "${BASE_CONFIG_PATH}/." liberty:/opt/IBM/i2analyze/toolkit/configurati
 docker cp "${BASE_CONFIG_PATH}/." zookeeper:/opt/IBM/i2analyze/toolkit/configuration
 docker cp "${BASE_CONFIG_PATH}/." solr:/opt/IBM/i2analyze/toolkit/configuration
 docker cp "${BASE_CONFIG_PATH}/." solr2:/opt/IBM/i2analyze/toolkit/configuration
+
+#Reset base configuration
+cp -r "${CONFIG_MODS_PATH}/${dbDialect}/base/." "${DEFAULT_CONFIG_PATH}"
+
 #Copy Default Config
-docker cp "${DEFAULT_CONFIG_PATH}/." admin_client:/opt/IBM/i2analyze/toolkit/configuration
-docker cp "${DEFAULT_CONFIG_PATH}/." liberty:/opt/IBM/i2analyze/toolkit/configuration
-docker cp "${DEFAULT_CONFIG_PATH}/." zookeeper:/opt/IBM/i2analyze/toolkit/configuration
-docker cp "${DEFAULT_CONFIG_PATH}/." solr:/opt/IBM/i2analyze/toolkit/configuration
-docker cp "${DEFAULT_CONFIG_PATH}/." solr2:/opt/IBM/i2analyze/toolkit/configuration
+pushd ${SCRIPTS_PATH}
+. copyConfiguration $dbDialect
+popd
+docker cp "${IMAGES_PATH}/${dbDialect}/admin_client/configuration/." admin_client:/opt/IBM/i2analyze/toolkit/configuration
+docker cp "${IMAGES_PATH}/${dbDialect}/liberty/configuration/." liberty:/opt/IBM/i2analyze/toolkit/configuration
+docker cp "${IMAGES_PATH}/common/zookeeper/configuration/." zookeeper:/opt/IBM/i2analyze/toolkit/configuration
+docker cp "${IMAGES_PATH}/common/solr/configuration/." solr:/opt/IBM/i2analyze/toolkit/configuration
+docker cp "${IMAGES_PATH}/common/solr2/configuration/." solr2:/opt/IBM/i2analyze/toolkit/configuration
 
 #Change the ownership of the copied files
-docker exec -u root liberty chown -R i2analyze:db2iusr1 /opt/IBM/i2analyze/toolkit/configuration
-docker exec -u root admin_client chown -R i2analyze:db2iusr1 /opt/IBM/i2analyze/toolkit/configuration
+docker exec -u root admin_client chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration
+docker exec -u root liberty chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration
 docker exec -u root zookeeper chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration
 docker exec -u root solr chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration
 docker exec -u root solr2 chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration
 
 # If HTTP Server exists then reset the configuration
 contExists="$(containerExists ihs)"
-if [ "$contExists" -eq 1 ]; then
+if [[ "$contExists" -eq 1 ]]; then
     docker exec ihs sh -c "rm -rf /opt/IBM/i2analyze/toolkit/configuration/*"
-    docker cp "${BASE_CONFIG_PATH}/." ihs:/opt/IBM/i2analyze/toolkit/configuration
-    docker cp "${DEFAULT_CONFIG_PATH}/." ihs:/opt/IBM/i2analyze/toolkit/configuration
+    docker cp "${IMAGES_PATH}/common/ihs/configuration/." ihs:/opt/IBM/i2analyze/toolkit/configuration
     docker exec -u root ihs chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration
 fi
-
 
 # Searching and replacing ssl tag, removing clientAuthenticationSupported
 docker exec -u i2analyze liberty sh -c "cd /opt/IBM/i2analyze/deploy/wlp/usr/servers/opal-server && \
@@ -92,23 +105,36 @@ docker exec -u i2analyze solr2 /opt/IBM/i2analyze/toolkit/scripts/setup -t stopS
 docker exec -u i2analyze solr /opt/IBM/i2analyze/toolkit/scripts/setup -t startSolrNodes --hostname solr
 docker exec -u i2analyze solr2 /opt/IBM/i2analyze/toolkit/scripts/setup -t startSolrNodes --hostname solr2
 
-# Resetting the DB2COMM property in the db2 server
-docker exec -u db2inst1 db2 db2set DB2COMM=tcpip
+if [[ $dbDialect == "db2" ]]; then
+    # Resetting the DB2COMM property in the db2 server
+    docker exec -u db2inst1 db2 db2set DB2COMM=tcpip
 
-# Recataloging the database on the admin_client container
-docker exec -u i2analyze admin_client /opt/IBM/i2analyze/toolkit/scripts/setup -t recatalogRemoteDB2Nodes
-docker exec -u i2analyze admin_client /opt/IBM/i2analyze/toolkit/scripts/setup -t recatalogDB2Databases
+    # Recataloging the database on the admin_client container
+    docker exec -u i2analyze admin_client /opt/IBM/i2analyze/toolkit/scripts/setup -t recatalogRemoteDB2Nodes
+    docker exec -u i2analyze admin_client /opt/IBM/i2analyze/toolkit/scripts/setup -t recatalogDB2Databases
 
-# Recataloging the database on the liberty container
-docker exec -u i2analyze liberty /opt/IBM/i2analyze/toolkit/scripts/setup -t recatalogRemoteDB2Nodes
-docker exec -u i2analyze liberty /opt/IBM/i2analyze/toolkit/scripts/setup -t recatalogDB2Databases
+    # Recataloging the database on the liberty container
+    docker exec -u i2analyze liberty /opt/IBM/i2analyze/toolkit/scripts/setup -t recatalogRemoteDB2Nodes
+    docker exec -u i2analyze liberty /opt/IBM/i2analyze/toolkit/scripts/setup -t recatalogDB2Databases
+elif [[ $dbDialect == "sqlserver" ]]; then
+    # Resetting the connection properties in the sqlserver server
+    docker exec -t sqlserver /opt/mssql/bin/mssql-conf unset network.tlscert
+    docker exec -t sqlserver /opt/mssql/bin/mssql-conf unset network.tlskey
+    docker exec -t sqlserver /opt/mssql/bin/mssql-conf unset network.tlsprotocols
+    docker exec -t sqlserver /opt/mssql/bin/mssql-conf unset network.forceencryption
+fi
 
 # Deploying liberty
 docker exec -u i2analyze liberty /opt/IBM/i2analyze/toolkit/scripts/setup -t deployLiberty
 
-# Restart db2
-docker exec -u db2inst1     db2         db2stop
-docker exec -u db2inst1     db2         db2start
+if [[ $dbDialect == "db2" ]]; then
+    # Restart db2
+    docker exec -u db2inst1     db2         db2stop
+    docker exec -u db2inst1     db2         db2start
+elif [[ $dbDialect == "sqlserver" ]]; then
+    # Restart sqlserver
+    docker restart sqlserver
+fi
 
 # Starting liberty
 docker exec -u i2analyze liberty /opt/IBM/i2analyze/toolkit/scripts/setup -t startLiberty
diff --git a/src/scripts/setupSecurity b/src/scripts/setupSecurity
--- a/src/scripts/setupSecurity
+++ b/src/scripts/setupSecurity
@@ -14,8 +14,9 @@
 #                                                                                   #
 #  Script to deploy a complete SSL deployment of i2 Analyze                         #
 #                                                                                   #
-#  Usage : setupSecurity [<configurationDir>]                                       #
+#  Usage : setupSecurity [<configurationDir>] [<dbDialect>]                         #
 #  Defaults to ssl configuration directory                                          #
+#  Defaults to current dialect                                                      #
 #                                                                                   #
 #####################################################################################
 
@@ -34,19 +35,27 @@ if [[ $configurationDir != "client_cert_ssl" &&  $configurationDir != "ssl" &&  
     exit 1
 fi
 
+dbDialect=${2:-${DB_DIALECT}}
+if [[ $dbDialect != "sqlserver" &&  $dbDialect != "db2" ]]; then
+    echo "Error: Unrecognized dialect."
+    exit 1
+fi
+
 pushd ${SCRIPTS_PATH}
-. updateServerConfigurations $configurationDir
+. updateServerConfigurations $configurationDir $dbDialect
 popd
 
 header "Enabling SSL on all servers"
 
 output "Redeploying configuration"
-output "Recataloging the database on the admin_client container"
-docker exec -u i2analyze admin_client /opt/IBM/i2analyze/toolkit/scripts/setup -t recatalogRemoteDB2Nodes
-docker exec -u i2analyze admin_client /opt/IBM/i2analyze/toolkit/scripts/setup -t recatalogDB2Databases
-output "Recataloging the database on the liberty container"
-docker exec -u i2analyze liberty /opt/IBM/i2analyze/toolkit/scripts/setup -t recatalogRemoteDB2Nodes
-docker exec -u i2analyze liberty /opt/IBM/i2analyze/toolkit/scripts/setup -t recatalogDB2Databases
+if [[ $dbDialect == "db2" ]]; then
+    output "Recataloging the database on the admin_client container"
+    docker exec -u i2analyze admin_client /opt/IBM/i2analyze/toolkit/scripts/setup -t recatalogRemoteDB2Nodes
+    docker exec -u i2analyze admin_client /opt/IBM/i2analyze/toolkit/scripts/setup -t recatalogDB2Databases
+    output "Recataloging the database on the liberty container"
+    docker exec -u i2analyze liberty /opt/IBM/i2analyze/toolkit/scripts/setup -t recatalogRemoteDB2Nodes
+    docker exec -u i2analyze liberty /opt/IBM/i2analyze/toolkit/scripts/setup -t recatalogDB2Databases
+fi
 
 output "Deploying Liberty"
 docker exec -u i2analyze liberty /opt/IBM/i2analyze/toolkit/scripts/setup -t deployLiberty
@@ -60,8 +69,35 @@ fi
 output "Update the Solr configuration on the ZooKeeper server"
 docker exec -u i2analyze zookeeper /opt/IBM/i2analyze/toolkit/scripts/setup -t createAndUploadSolrConfig --hostname zookeeper
 
-output "Updating the DB2 configuration"
-docker exec -u db2inst1 db2 db2set DB2COMM=ssl
+if [[ $dbDialect == "db2" ]]; then
+    output "Updating the DB2 configuration"
+    docker exec -u db2inst1 db2 db2set DB2COMM=ssl
+
+    #Configure clients
+    docker exec -u db2inst1 -t liberty db2 update dbm cfg using SSL_CLNT_KEYDB /opt/IBM/keys/stores/i2-db2-truststore.kdb SSL_CLNT_STASH /opt/IBM/keys/stores/i2-db2-truststore.sth
+    docker exec -u db2inst1 -t admin_client db2 update dbm cfg using SSL_CLNT_KEYDB /opt/IBM/keys/stores/i2-db2-truststore.kdb SSL_CLNT_STASH /opt/IBM/keys/stores/i2-db2-truststore.sth
+    docker exec -u db2inst1 -t etl_client db2 update dbm cfg using SSL_CLNT_KEYDB /opt/IBM/keys/stores/i2-db2-truststore.kdb SSL_CLNT_STASH /opt/IBM/keys/stores/i2-db2-truststore.sth
+
+elif [[ $dbDialect == "sqlserver" ]]; then
+    output "Enabling Sql Server secure connection"
+    docker exec -t sqlserver /opt/mssql/bin/mssql-conf set network.tlscert /opt/IBM/keys/responses/sqlserver-key.cer
+    docker exec -t sqlserver /opt/mssql/bin/mssql-conf set network.tlskey /opt/IBM/keys/stores/i2-sqlserver-key.key
+    docker exec -t sqlserver /opt/mssql/bin/mssql-conf set network.tlsprotocols 1.2 
+    docker exec -t sqlserver /opt/mssql/bin/mssql-conf set network.forceencryption 1
+
+    #Configure clients
+    docker cp "${IMAGES_PATH}/common/ca/ca/CA.cer" liberty:/usr/share/ca-certificates/CA.cer
+    docker cp "${IMAGES_PATH}/common/ca/ca/CA.cer" etl_client:/usr/share/ca-certificates/CA.cer
+    docker cp "${IMAGES_PATH}/common/ca/ca/CA.cer" admin_client:/usr/share/ca-certificates/CA.cer
+
+    docker exec -u root liberty bash -c "grep -q \"CA.cer\" /etc/ca-certificates.conf || echo \"CA.cer\" >> /etc/ca-certificates.conf"
+    docker exec -u root etl_client bash -c "grep -q \"CA.cer\" /etc/ca-certificates.conf || echo \"CA.cer\" >> /etc/ca-certificates.conf"
+    docker exec -u root admin_client bash -c "grep -q \"CA.cer\" /etc/ca-certificates.conf || echo \"CA.cer\" >> /etc/ca-certificates.conf"
+
+    docker exec -u root -t liberty update-ca-certificates
+    docker exec -u root -t etl_client update-ca-certificates
+    docker exec -u root -t admin_client update-ca-certificates
+fi
 
 if [[ $configurationDir == "ihs_ssl" || $configurationDir == "client_cert_ssl" ]]; then
     output "Updating the HTTP Server configuration"
@@ -77,10 +113,18 @@ docker exec -u i2analyze    liberty     /opt/IBM/i2analyze/toolkit/scripts/setup
 docker exec -u i2analyze    solr        /opt/IBM/i2analyze/toolkit/scripts/setup -t stopSolrNodes   --hostname solr         &>/dev/null || true
 docker exec -u i2analyze    solr2       /opt/IBM/i2analyze/toolkit/scripts/setup -t stopSolrNodes   --hostname solr2        &>/dev/null || true
 docker exec -u i2analyze    zookeeper   /opt/IBM/i2analyze/toolkit/scripts/setup -t stopZkHosts     --hostname zookeeper    &>/dev/null || true
-docker exec -u db2inst1     db2         db2stop                                                                             &>/dev/null || true
+if [[ $dbDialect == "db2" ]]; then
+    docker exec -u db2inst1     db2         db2stop                                                                         &>/dev/null || true
+elif [[ $dbDialect == "sqlserver" ]]; then
+    docker stop sqlserver
+fi
 
 output "Starting the containers"
-docker exec -u db2inst1     db2         db2start
+if [[ $dbDialect == "db2" ]]; then
+    docker exec -u db2inst1     db2         db2start
+elif [[ $dbDialect == "sqlserver" ]]; then
+    docker start sqlserver
+fi
 docker exec -u i2analyze    zookeeper   /opt/IBM/i2analyze/toolkit/scripts/setup -t startZkHosts    --hostname zookeeper
 docker exec -u i2analyze    solr        /opt/IBM/i2analyze/toolkit/scripts/setup -t startSolrNodes  --hostname solr
 docker exec -u i2analyze    solr2       /opt/IBM/i2analyze/toolkit/scripts/setup -t startSolrNodes  --hostname solr2
diff --git a/src/scripts/updateServerConfigurations b/src/scripts/updateServerConfigurations
--- a/src/scripts/updateServerConfigurations
+++ b/src/scripts/updateServerConfigurations
@@ -14,7 +14,8 @@
 #                                                                                   #
 #  Script to update the configuration on all containers                             #
 #                                                                                   #
-#  Usage : updateServerConfigurations [<configModsName>]                            #
+#  Usage : updateServerConfigurations <configModsName> [<dbDialect>]                #
+#  Defaults to current dialect                                                      #
 #                                                                                   #
 #####################################################################################
 
@@ -25,40 +26,58 @@ pushd ..
 . ${UTILS_PATH}/functions
 
 configModsName=$1
+dbDialect=${2:-${DB_DIALECT}}
+
+if [[ $dbDialect != "sqlserver" &&  $dbDialect != "db2" ]]; then
+    echo "Error: Unrecognized dialect."
+    exit 1
+fi
 
 if [[ -z "$configModsName" ]]; then
     echo "Error: Configuration not specified."
     exit 1
 fi
 
-if [[ ! -d "${CONFIG_MODS_PATH}/$configModsName" ]]; then
+if [[ ! -d "${CONFIG_MODS_PATH}/${dbDialect}/$configModsName" ]]; then
     echo "Error: Specified configuration $configModsName does not exist."
     exit 1
 fi
 
-output "Copy the specified configuration to each container"
-#Copy Modifications
-docker cp "${CONFIG_MODS_PATH}/${configModsName}/." admin_client:/opt/IBM/i2analyze/toolkit/configuration
-docker cp "${CONFIG_MODS_PATH}/${configModsName}/." ihs:/opt/IBM/i2analyze/toolkit/configuration
-docker cp "${CONFIG_MODS_PATH}/${configModsName}/." liberty:/opt/IBM/i2analyze/toolkit/configuration
-docker cp "${CONFIG_MODS_PATH}/${configModsName}/." zookeeper:/opt/IBM/i2analyze/toolkit/configuration
-docker cp "${CONFIG_MODS_PATH}/${configModsName}/." solr:/opt/IBM/i2analyze/toolkit/configuration
-docker cp "${CONFIG_MODS_PATH}/${configModsName}/." solr2:/opt/IBM/i2analyze/toolkit/configuration
+#Copy base configuration
+pushd ${SCRIPTS_PATH}
+. copyConfiguration $dbDialect
+popd
 
-# Make sure the credentials file is up-to-date
-docker cp "${DEFAULT_CONFIG_PATH}/environment/credentials.properties" admin_client:/opt/IBM/i2analyze/toolkit/configuration/environment/credentials.properties
-docker cp "${DEFAULT_CONFIG_PATH}/environment/credentials.properties" ihs:/opt/IBM/i2analyze/toolkit/configuration/environment/credentials.properties
-docker cp "${DEFAULT_CONFIG_PATH}/environment/credentials.properties" liberty:/opt/IBM/i2analyze/toolkit/configuration/environment/credentials.properties
-docker cp "${DEFAULT_CONFIG_PATH}/environment/credentials.properties" zookeeper:/opt/IBM/i2analyze/toolkit/configuration/environment/credentials.properties
-docker cp "${DEFAULT_CONFIG_PATH}/environment/credentials.properties" solr:/opt/IBM/i2analyze/toolkit/configuration/environment/credentials.properties
-docker cp "${DEFAULT_CONFIG_PATH}/environment/credentials.properties" solr2:/opt/IBM/i2analyze/toolkit/configuration/environment/credentials.properties
+#Copy Modifications to folders
+cp -r "${CONFIG_MODS_PATH}/${dbDialect}/${configModsName}/." ${IMAGES_PATH}/common/zookeeper/configuration
+cp -r "${CONFIG_MODS_PATH}/${dbDialect}/${configModsName}/." ${IMAGES_PATH}/common/solr/configuration
+cp -r "${CONFIG_MODS_PATH}/${dbDialect}/${configModsName}/." ${IMAGES_PATH}/common/solr2/configuration
+cp -r "${CONFIG_MODS_PATH}/${dbDialect}/${configModsName}/." ${IMAGES_PATH}/common/ihs/configuration
+
+cp -r "${CONFIG_MODS_PATH}/${dbDialect}/${configModsName}/." ${IMAGES_PATH}/${dbDialect}/liberty/configuration
+cp -r "${CONFIG_MODS_PATH}/${dbDialect}/${configModsName}/." ${IMAGES_PATH}/${dbDialect}/admin_client/configuration
+
+output "Copy the configuration to each container"
+#Copy Modifications
+docker cp "${IMAGES_PATH}/${dbDialect}/admin_client/configuration/." admin_client:/opt/IBM/i2analyze/toolkit/configuration
+docker cp "${IMAGES_PATH}/${dbDialect}/liberty/configuration/." liberty:/opt/IBM/i2analyze/toolkit/configuration
+
+docker cp "${IMAGES_PATH}/common/zookeeper/configuration/." zookeeper:/opt/IBM/i2analyze/toolkit/configuration
+docker cp "${IMAGES_PATH}/common/solr/configuration/." solr:/opt/IBM/i2analyze/toolkit/configuration
+docker cp "${IMAGES_PATH}/common/solr2/configuration/." solr2:/opt/IBM/i2analyze/toolkit/configuration
 
 #Change the ownership of the copied files
-docker exec -u root liberty chown -R i2analyze:db2iusr1 /opt/IBM/i2analyze/toolkit/configuration
-docker exec -u root admin_client chown -R i2analyze:db2iusr1 /opt/IBM/i2analyze/toolkit/configuration
+docker exec -u root admin_client chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration
+docker exec -u root liberty chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration
 docker exec -u root zookeeper chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration
 docker exec -u root solr chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration
 docker exec -u root solr2 chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration
-docker exec -u root ihs chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration
+
+# If HTTP Server exists then reset the configuration
+contExists="$(containerExists ihs)"
+if [[ "$contExists" -eq 1 ]]; then
+    docker cp "${IMAGES_PATH}/common/ihs/configuration/." ihs:/opt/IBM/i2analyze/toolkit/configuration
+    docker exec -u root ihs chown -R i2analyze:i2analyze /opt/IBM/i2analyze/toolkit/configuration
+fi
 
 popd
