v2.2.0 public release

diff --git a/src/images/db2/db2/Dockerfile b/src/images/db2/db2/Dockerfile
--- a/src/images/db2/db2/Dockerfile
+++ b/src/images/db2/db2/Dockerfile
@@ -1,5 +1,5 @@
 #/********************************************************************************
-# * (C) Copyright IBM Corporation 2018, 2019.
+# * (C) Copyright IBM Corporation 2018, 2020.
 # *
 # * This program and the accompanying materials are made available under the
 # * terms of the Eclipse Public License 2.0 which is available at
@@ -26,10 +26,11 @@ COPY --chown=db2inst1:db2iadm1 db2nodes.cfg /home/db2inst1/sqllib/db2nodes.cfg
 #Create a group for securing the keys
 RUN usermod -a -G keys db2inst1
 
-RUN echo "db2start || echo \"Error starting DB2\"" >> /opt/IBM/startupExt
+RUN echo ". /home/db2inst1/sqllib/db2profile && db2start || echo \"Error starting DB2\"" >> /opt/IBM/startupExt
 
 USER db2inst1:db2iadm1
-RUN /home/db2inst1/sqllib/adm/db2licm -a /opt/IBM/awse_o/db2/license/db2awse_o.lic
+
+RUN /home/db2inst1/sqllib/adm/db2licm -a /opt/IBM/adv_vpc/db2/license/db2adv_vpc.lic
 
 EXPOSE 50000 50001
 
